//! Secure memory handling for sensitive data

use secrecy::{ExposeSecret, SecretSlice};
use subtle::ConstantTimeEq;

/// A secure byte container that automatically zeros its memory on drop.
///
/// This is a type alias for `secrecy::SecretSlice<u8>` (`SecretBox<[u8]>`), which provides:
/// - Automatic memory zeroing on drop
/// - Prevention of accidental logging via Debug/Display
/// - Zero-copy construction from `Vec<u8>` (no intermediate `String` allocation)
/// - Industry-standard security practices
///
/// # Security
///
/// The contained data is automatically zeroed when the value is dropped,
/// using the `zeroize` crate which provides compiler-fence-backed guarantees
/// that the zeroing operation won't be optimized away.
///
/// # Usage
///
/// Access the underlying bytes using `.expose_secret()`, or get a string
/// view using `.as_str()` (from the [`SecureStringExt`] trait):
///
/// ```rust
/// use api_keys_simplified::{SecureString, SecureStringExt, ExposeSecret};
///
/// let secret = SecureString::from("my_secret".to_string().into_bytes());
/// let value: &str = secret.as_str();
/// let bytes: &[u8] = secret.expose_secret();
/// ```
///
/// # Design: Why No `Deref<Target=str>`?
///
/// This type **intentionally does NOT implement `Deref`** to maintain security:
///
/// - **Explicit access**: Requires `.expose_secret()` or `.as_str()` call, making code auditable
/// - **Prevents silent leakage**: No implicit coercion to `&str` in logs/errors
/// - **Grep-able security**: Easy to audit with `git grep "\.expose_secret\(\)\|\.as_str\(\)"`
/// - **Industry standard**: Uses the battle-tested `secrecy` crate
pub type SecureString = SecretSlice<u8>;

/// Extension trait to add convenience methods to SecureString
pub trait SecureStringExt {
    /// Returns the length of the secret data in bytes.
    fn len(&self) -> usize;

    /// Returns true if the secret data is empty.
    fn is_empty(&self) -> bool;

    /// Constant-time equality comparison.
    fn eq(&self, other: &Self) -> bool;

    /// Returns the secret data as a UTF-8 string slice.
    ///
    /// API keys generated by this crate are always valid UTF-8 (composed of
    /// ASCII prefix, separator, base64url, and hex checksum characters).
    ///
    /// # Panics
    ///
    /// Panics if the underlying bytes are not valid UTF-8. This would indicate
    /// a bug in the key generator, not a user error.
    fn as_str(&self) -> &str;
}

impl SecureStringExt for SecureString {
    fn len(&self) -> usize {
        self.expose_secret().len()
    }

    fn is_empty(&self) -> bool {
        self.expose_secret().is_empty()
    }

    fn eq(&self, other: &Self) -> bool {
        self.expose_secret().ct_eq(other.expose_secret()).into()
    }

    fn as_str(&self) -> &str {
        std::str::from_utf8(self.expose_secret())
            .expect("SecureString contents must be valid UTF-8")
    }
}

/// Creates a [`SecureString`] from a [`String`], consuming the string and
/// converting it to bytes internally. The `String`'s backing allocation is
/// moved (via `into_bytes`) so no unzeroized copy is left behind.
///
/// This is a convenience for test code. Production callers should construct
/// `SecureString::from(vec)` directly from owned bytes.
#[cfg(test)]
pub(crate) fn new_secure_string(s: String) -> SecureString {
    SecureString::from(s.into_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secure_string_creation() {
        let secret = new_secure_string("my_secret".to_string());
        assert_eq!(secret.as_str(), "my_secret");
        assert_eq!(secret.len(), 9);
        assert!(!secret.is_empty());
    }

    #[test]
    fn test_secure_string_redaction() {
        let secret = new_secure_string("sensitive_data".to_string());

        // Debug output should be redacted by secrecy crate
        let debug_output = format!("{:?}", secret);
        assert!(!debug_output.contains("sensitive_data"));
        assert!(debug_output.contains("Secret"));
    }

    #[test]
    fn test_secure_string_empty() {
        let empty = new_secure_string(String::new());
        assert!(empty.is_empty());
        assert_eq!(empty.len(), 0);
    }

    #[test]
    fn test_expose_secret() {
        let secret = new_secure_string("test".to_string());
        let reference: &[u8] = secret.expose_secret();
        assert_eq!(reference, b"test");
    }

    #[test]
    fn test_as_str() {
        let secret = new_secure_string("hello_world".to_string());
        assert_eq!(secret.as_str(), "hello_world");
    }

    #[test]
    fn test_from_vec() {
        let secret = SecureString::from(vec![104, 101, 108, 108, 111]); // "hello"
        assert_eq!(secret.as_str(), "hello");
        assert_eq!(secret.len(), 5);
    }

    #[test]
    fn test_constant_time_eq() {
        let a = new_secure_string("same_value".to_string());
        let b = new_secure_string("same_value".to_string());
        let c = new_secure_string("diff_value".to_string());
        assert!(a.eq(&b));
        assert!(!a.eq(&c));
    }
}
